server.port=8080

spring.application.name=profile-api
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/fabric}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8081}

fabric.kafka.topic.profile-events=profile.events

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.prometheus.metrics.export.enabled=true

logging.level.com.myfabric=DEBUG
logging.level.org.apache.kafka=WARN
