apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-config
  namespace: my-fabric
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry-service:8081"
  MONGODB_URI: "mongodb://mongodb-service:27017/fabric"
  CONSUMER_GROUP_ID: "profile-consumer-group"
