server.port=8082

spring.application.name=dlq-consumer
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/fabric}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${CONSUMER_GROUP_ID:dlq-consumer-group}
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8081}
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME:dlqconsumer}" password="${KAFKA_PASSWORD:dlq-secret}";

management.endpoints.web.exposure.include=health,info,prometheus

logging.level.com.myfabric=DEBUG
logging.level.org.apache.kafka=INFO
